### ISSUE TITLE
TypeScript error occurs with @line/liff v2.22.0

### ISSUE THREAD

**Issue by taro-yanagiya** [line/liff-mock#17]
TypeScript error occurs when I upgrade LIFF SDK to v2.22.0.

1. In [npm-typescript-example](https://github.com/line/liff-mock/tree/main/examples/npm-typescript-example), upgrade LIFF SDK to v2.22.0
2. run `npx tsc`

```
$ npx tsc
src/index.ts:16:7 - error TS2345: Argument of type '{ liffId: string; mock: boolean; }' is not assignable to parameter of type 'Config'.
  Object literal may only specify known properties, and 'mock' does not exist in type 'Config'.

16       mock: true,
         ~~~~~~~~~~


Found 1 error in src/index.ts:16
```

**Comment by cola119** [comment]
Thank you for the report @taro-yanagiya! I could reproduce the error and I'll take a look into it :)

**Comment by bomb-kst** [comment]
@taro-yanagiya same here

`Argument of type '{ liffId: string; mock: boolean; }' is not assignable to parameter of type 'Config'.
  Object literal may only specify known properties, and 'mock' does not exist in type 'Config'.ts(2345)`

![image](https://github.com/line/liff-mock/assets/118168383/bde87f5e-d5b3-4bfb-b1b0-af55c22d322f)

@cola119 Once you solve this, could you please let us to know would be appreciated. Thank you

**Comment by cola119** [comment]
@bomb-kst Thank you for reporting. We have investigated the cause and found that the issue is due to a change in the way type definitions are exported since v2.22.0.

Until we release the fix, please try the following workaround, which should resolve the type error:

```diff
import { ExtendedInit, LiffMockApi } from '@line/liff-mock';

- declare module '@line/liff' {
+ declare module '@line/liff/exports' {
  interface Liff {
    init: ExtendedInit;
    $mock: LiffMockApi;
  }
}
```

**Comment by cola119** [comment]
Now we are working on the fix in LIFF SDK.

**Comment by cola119** [comment]
Addressed in [`@line/liff@2.22.4`](https://www.npmjs.com/package/@line/liff/v/2.22.4)
