### PR TITLE
Declare `@line/liff` module types in the entry file

### LINKED ISSUE #17: TypeScript error occurs with @line/liff v2.22.0
TypeScript error occurs when I upgrade LIFF SDK to v2.22.0.

1. In [npm-typescript-example](https://github.com/line/liff-mock/tree/main/examples/npm-typescript-example), upgrade LIFF SDK to v2.22.0
2. run `npx tsc`

```
$ npx tsc
src/index.ts:16:7 - error TS2345: Argument of type '{ liffId: string; mock: boolean; }' is not assignable to parameter of type 'Config'.
  Object literal may only specify known properties, and 'mock' does not exist in type 'Config'.

16       mock: true,
         ~~~~~~~~~~


Found 1 error in src/index.ts:16
```

### PR DESCRIPTION
**Pull request by cola119**
Fix https://github.com/line/liff-mock/issues/17

This PR fixes the type incompatibility issue reported in #17 to declare the extended type definitions for `@line/liff` module in the entry file of LIFF Mock. I've confirmed this declaration works fine with LIFF SDK for each version.

| with v2.19.0 | with v2.22.0 |
| -- | -- |
| image | image |

### CODE REVIEW

**Review by sugarshin — APPROVED** [review]
LGTM

**Comment by cola119** [comment]
We concluded to make changes to LIFF SDK so that LIFF Plugins can extend the LIFF type with `declare module '@line/liff' {`.
